# NE 250 – Homework 3
## Problem 5
###### 10/20/2017

In [1]:
import numpy as np

The inverse, $\textbf{A}^{-1}$ of a square matrix, $\textbf{A}$,  is equal to the adjugate of the matrix, $\textbf{A}^{\dagger}$ divided by the determinant of $\textbf{A}$.

$$ \textbf{A}^{-1} = \frac{\textbf{A}^{\dagger}}{\det{\textbf{A}}} $$

We can manipulate this expression to find

$$ (\det{\textbf{A}})\mathbb{1} = \textbf{A}^{\dagger}\textbf{A} $$

Since we are looking for a self-adjugate matrix, $\textbf{A}^{\dagger} = \textbf{A}$, and 

$$ (\det{\textbf{A}})\mathbb{1} = \textbf{A}^2 .$$

Then, taking the square root of both sides,

$$ \left(\sqrt{\det{\textbf{A}}}\right)\mathbb{1} = \textbf{A} .$$

$$ \textbf{A} = \begin{bmatrix} a & b & c \\
                                d & e & f \\
                                g & h & i \end{bmatrix} =
                \begin{bmatrix} \sqrt{\det{\textbf{A}}} & 0 & 0 \\
                                0 & \sqrt{\det{\textbf{A}}} & 0 \\
                                0 & 0 & \sqrt{\det{\textbf{A}}} \end{bmatrix}. $$
                
$$ a = e = i = \sqrt{\det{\textbf{A}}} $$
$$ \textbf{A} = \begin{bmatrix} a & 0 & 0 \\
                                0 & a & 0 \\
                                0 & 0 & a \end{bmatrix} = $$
and

$$ \det{\textbf{A}} = a \begin{vmatrix} a & 0 \\ 0 & a \end{vmatrix} $$
$$ \det{\textbf{A}} = a (a^2) $$
$$ \det{\textbf{A}} = a^3 .$$

We know that $a = \sqrt{\det{\textbf{A}}}$, so
$$ a = \sqrt{a^3} $$
$$ a = a^{\frac{3}{2}} $$
$$ a = 1 $$
$$\boxed{ \textbf{A} = \mathbb{1} }$$

We can test this using the functions defined in problem 4.

In [2]:
def adjugate(matrix):    
    cofactor_matrix = cofactor(matrix)
    adjugate_matrix = transpose(cofactor_matrix)
    return adjugate_matrix  

def cofactor(matrix):
    minors_matrix = minors(matrix)
    cofactor_matrix = np.copy(minors_matrix)
    for i in range(len(cofactor_matrix)):
        for j in range(len(cofactor_matrix[0])):
                cofactor_matrix[i,j] *= (-1)**(i+j)
    return cofactor_matrix

def transpose(matrix):
    transpose_matrix = np.empty_like(matrix)
    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            transpose_matrix[j,i] = matrix[i,j]
    return transpose_matrix

def minors(matrix):
    minors_matrix = np.empty_like(matrix)
    for i in range(len(minors_matrix)):
        for j in range(len(minors_matrix[0])):
            minors_matrix[i,j] = minor(matrix,i,j)
    return minors_matrix

def minor(matrix,i,j):
    submatrix = np.copy(matrix)
    submatrix = np.delete(submatrix,i,axis=0)
    submatrix = np.delete(submatrix,j,axis=1)
    minor_ij = determinant(submatrix)
    return minor_ij

def determinant(matrix):
    assert len(matrix) == len(matrix[0])
    if len(matrix) == 2:
        return matrix[0,0]*matrix[1,1]-matrix[0,1]*matrix[1,0]
    else:
        signed_minors = []
        for j in range(len(matrix[0])):
            if (j+2)%2 == 1:
                sign = -1
            else: sign = 1
            signed_minors.append(matrix[0,j]*sign*minor(matrix,0,j))
        return sum(signed_minors)

In [3]:
A = np.identity(3)
print('A = \n',A)
print('Adjugate of A = \n',adjugate(A))

A = 
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
Adjugate of A = 
 [[ 1. -0.  0.]
 [-0.  1. -0.]
 [ 0. -0.  1.]]
